🔀 동아리 리스트 구현
GSM-MSG/MSG-BackEnd-V2 pull request #119
Opened 2022-05-30 05:34 UTC by Huuuunee

Get요청으로 afterSchool로 요청이 왔을때 리스트를 반환합니다.
### response값
``` json
{
	"header": {"Authorization": "Token"},
	"QueryString": {
		"season" : "FIRST",
		"week" : "MON",
		"grade" : 1
	}
}
```
### request값
``` json
[
	{
		"afterSchool"{
				"id" : 1,
				"title" : "컴활",
				"week" : "MON",
				"grade" : 1,
				"personnel" : 13,
				"maxPersonnel" : 25,
				"isOpened" : Boolean
		}
		"isApplied" : Boolean
	},
	{
		"afterSchool"{
				"id" : 1,
				"title" : "컴활",
				"week" : "MON",
				"grade" : 1,
				"personnel" : 13,
				"maxPersonnel" : 25,
				"isOpened" : Boolean
		}
		"isApplied" : Boolean
	}	
]
```

2022-05-30 05:35 UTC, chanwoo00106 requested changes

2022-05-30 05:35 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
query에서 나오는 값은 무조건 string입니다

2022-05-30 05:35 UTC, kimsh153 approved these changes

2022-05-30 05:35 UTC, sagwamatrlawns approved these changes

2022-05-30 05:36 UTC, Huuuunee commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
아 그럼 grade제가 바꿔야하는건가요?

2022-05-30 05:36 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
글고 이거 그냥 한 번에 받고 dto까지 작성하는 게 좋을 것 같음

2022-05-30 05:38 UTC, Huuuunee commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
야 근데 GET인데 쿼리스트링을 dto로 해서 받을수있음?

2022-05-30 05:38 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
> 아 그럼 grade제가 바꿔야하는건가요?

당연하지 
저거 grade 출력해보면 string으로 뜸

2022-05-30 05:39 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
> 야 근데 GET인데 쿼리스트링을 dto로 해서 받을수있음?

당연

2022-05-30 05:39 UTC, Huuuunee commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
그건 이해하는데 저게 되는지 궁금해

2022-05-30 05:40 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
대신 querystring에서는 전부 string으로 받아야지

2022-05-30 05:41 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.service.ts
> +}
아무것도 작성을 안 했는데 pr은 왜 날림?

2022-05-30 05:41 UTC, baekteun commented on src/afterSchool/afterSchool.service.ts
> +}
???: PR날리고 커밋할거임

2022-05-30 05:41 UTC, Huuuunee commented on src/afterSchool/afterSchool.service.ts
> +}
위같은 상황을 나중에 만들기 싫었습니다 ㅎ

2022-05-30 05:41 UTC, chanwoo00106 commented on src/afterSchool/afterSchool.service.ts
> +}
흠...

2022-05-30 05:43 UTC, khs3994 approved these changes

2022-05-30 05:43 UTC, yoonjibin approved these changes
좋은 코드를 작성했네요!

2022-05-30 05:46 UTC, chanwoo00106 commented
> 좋은 코드를 작성했네요!

작성도 안 했는데 뭔 좋은 코드야

2022-05-30 05:47 UTC, baekteun commented
> > 좋은 코드를 작성했네요!
> 
> 작성도 안 했는데 뭔 좋은 코드야

아ㅋㅋ 이정도면 50% 완성이네

2022-05-30 05:48 UTC, chanwoo00106 commented
> 

;;;

2022-05-30 06:12 UTC, Huuuunee commented on src/afterSchool/afterSchool.controller.ts
> +    @Query('grade') grade: number,
[성공](https://github.com/GSM-MSG/MSG-BackEnd-V2/commit/7e3ff8630a2b9d71f9ea32ebe7583c6e25a60501)잘했지 ㅎㅎ

2022-05-30 06:17 UTC, louis7308 approved these changes

2022-05-30 06:34 UTC, chanwoo00106 commented on src/afterSchool/dto/listData.dto.ts
> +  @Type(() => String)
이거 뭐임 이렇게 하면 string 타입으로 바뀜?
관련 자료 있으면 보내봐

2022-05-30 06:41 UTC, Huuuunee commented on src/afterSchool/dto/listData.dto.ts
> +  @Type(() => String)
https://stackoverflow.com/questions/65486947/nestjs-transform-a-property-using-validationpipe-before-validation-execution-dur
이것 저것 보면서 따라한건데 값은 바껴서 잘나옴

2022-05-30 06:47 UTC, junseopark0331 approved these changes
LGTM

2022-05-30 06:50 UTC, chanwoo00106 commented on src/afterSchool/dto/listData.dto.ts
> +  @Type(() => String)
원래 값이 string인데 또 string으로 변환할 이유는 없다고 생각함

2022-05-30 06:51 UTC, chanwoo00106 commented on src/afterSchool/dto/listData.dto.ts
> +  @Type(() => String)
아니면 다른 이유가 있음?

2022-05-30 06:52 UTC, Huuuunee commented on src/afterSchool/dto/listData.dto.ts
> +  @Type(() => String)
아하 예제 보다보니까 그것도 써버렸다\

2022-05-30 11:07 UTC, chanwoo00106 approved these changes

2022-06-01 12:46 UTC, jongjin1010 approved these changes

2022-06-05 12:56 UTC, chanwoo00106 commented
git pull origin main

2022-06-07 02:41 UTC, merged