Feat/entity
GSM-MSG/MSG-BackEnd-V2 pull request #126
Opened 2022-06-03 04:00 UTC by yoonjibin

방과후테이블에서 grade와 dayOfWeek분리

2022-06-03 04:10 UTC, baekteun approved these changes

2022-06-03 04:34 UTC, kimsh153 approved these changes

2022-06-03 05:06 UTC, sagwamatrlawns approved these changes

2022-06-03 05:37 UTC, jjaejjae12 approved these changes

2022-06-03 05:45 UTC, louis7308 approved these changes

2022-06-03 06:01 UTC, louis7308 commented on src/Entities/DayOfWeek.entity.ts
> +}
이부분 ManyToOne 하지 마시고 OneToMany로 하신 뒤에 따로 afterSchoolList 테이블하나더 빼서 그 테이블에다가 ManyToOne 때려 박아서 나중에 조회할때 쉽게 작성하는게 좋을거같아요

2022-06-03 06:01 UTC, louis7308 commented on src/Entities/Grade.entity.ts
> +}
이부분 ManyToOne 하지 마시고 OneToMany로 하신 뒤에 따로 afterSchoolList 테이블하나더 빼서 그 테이블에다가 ManyToOne 때려 박아서 나중에 조회할때 쉽게 작성하는게 좋을거같아요

2022-06-03 06:01 UTC, louis7308 commented on src/Entities/AfterSchool.entity.ts
> +  grade: number[];
이부분은 따로 테이블에서 뺄거니 없어도 되지 않을까요??

2022-06-03 06:04 UTC, louis7308 requested changes
approve 잘못때림

2022-06-03 07:11 UTC, khs3994 approved these changes

2022-06-03 07:18 UTC, chanwoo00106 approved these changes
냠

2022-06-04 06:22 UTC, louis7308 approved these changes

2022-06-04 06:27 UTC, merged