Fix/createdto
GSM-MSG/MSG-BackEnd-V2 pull request #129
Opened 2022-06-04 13:22 UTC by yoonjibin

생성할때 empty로 오는거 방지

2022-06-04 13:24 UTC, baekteun commented on src/Club/dto/createClub.dto.ts
> +  @IsNotEmpty()
연락처는 옵셔널맞음

2022-06-04 13:24 UTC, baekteun commented on src/Club/dto/editclub.dto.ts
> +  @IsNotEmpty()
ㄹㅇㅋㅋ

2022-06-04 13:25 UTC, baekteun commented
추가로 relatedLink에 isOptional 빼야될듯

2022-06-04 13:25 UTC, chanwoo00106 requested changes

2022-06-04 13:25 UTC, chanwoo00106 commented on src/Club/dto/ClubData.dto.ts
>    type: string;
이건 IsEnum으로 해줘

2022-06-04 13:25 UTC, chanwoo00106 requested changes

2022-06-04 13:25 UTC, chanwoo00106 commented on src/Club/dto/accept.dto.ts
>    type: string;
이것도

2022-06-04 13:26 UTC, chanwoo00106 requested changes
글고 db에서 보면 글자 길이 제한 한 거 있는데 그거 맞춰서 MaxLength 해서 제한을 두면 좋을 것 같음

2022-06-04 13:27 UTC, chanwoo00106 commented on src/Club/dto/createClub.dto.ts
> +  @IsNotEmpty()
아으 윤지빈
생각 없이 했네

2022-06-04 13:28 UTC, chanwoo00106 requested changes

2022-06-04 13:28 UTC, chanwoo00106 commented on src/Club/dto/kickuser.dto.ts
>    type: string;
이것도 enum으로

2022-06-04 13:29 UTC, chanwoo00106 commented on src/Club/dto/createClub.dto.ts
>    description: string;
description도 optional 아님?

2022-06-04 13:29 UTC, yoonjibin commented on src/Club/dto/createClub.dto.ts
>    description: string;
이건 아닌걸로 알고있는데?

2022-06-04 13:32 UTC, baekteun commented on src/Club/dto/relatedLink.dto.ts
>    url: string;
isUrl

2022-06-04 13:35 UTC, baekteun commented on src/Club/dto/createClub.dto.ts
>    description: string;
description 옵셔널 아님

2022-06-04 13:36 UTC, chanwoo00106 commented on src/Club/dto/createClub.dto.ts
>    type: string;
enum으로 ㄱㄱ

2022-06-04 13:36 UTC, chanwoo00106 commented on src/Club/dto/editclub.dto.ts
>    type: string;
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeennnnnnnnnnnnnnnnnnnnnnnnnnnnuuuuuuuuuuuuuuuuuuuuuuuuuuummmmmmmmmmmmmmmmm

2022-06-04 14:22 UTC, baekteun commented on src/Club/dto/createClub.dto.ts
>    bannerUrl: string;
얘도 isUrl걸어야할듯

2022-06-04 14:28 UTC, chanwoo00106 commented on src/Club/dto/createClub.dto.ts
>    bannerUrl: string;
isUrl에 protocol 같은 옵션도 있던데 그것도 해야 하는 거 아님?

2022-06-05 01:58 UTC, baekteun commented on src/Club/dto/accept.dto.ts
>      example: 's21024',
이거 s21024에서 s21024@gsm.hs.kr로 바꿔야할듯?

2022-06-05 01:58 UTC, baekteun commented on src/Club/dto/editclub.dto.ts
> +  @IsOptional()
```suggestion
```
isOptional아니였음ㄹㅇㅋㅋ

2022-06-05 04:44 UTC, khs3994 approved these changes

2022-06-05 04:47 UTC, louis7308 approved these changes

2022-06-05 05:18 UTC, dolong2 approved these changes

2022-06-05 05:43 UTC, Huuuunee approved these changes

2022-06-05 06:16 UTC, sagwamatrlawns approved these changes

2022-06-05 06:23 UTC, chanwoo00106 requested changes

2022-06-05 06:23 UTC, chanwoo00106 commented on src/Club/dto/createClub.dto.ts
> +  @Max(20)
Max는 숫자에 쓰는거임

2022-06-05 07:05 UTC, kimsh153 approved these changes

2022-06-05 12:23 UTC, chanwoo00106 requested changes

2022-06-05 12:23 UTC, chanwoo00106 commented on src/Club/dto/editclub.dto.ts
>    q: string;
여기도 MaxLength 해주셈

2022-06-05 12:24 UTC, chanwoo00106 commented
제목 같은 부분은 maxLength 해주셈
db에 varchar(글자길이) 해주잖어

2022-06-05 12:48 UTC, chanwoo00106 commented on src/Club/dto/createClub.dto.ts
>    bannerUrl: string;
protocol 옵션 없었어?

2022-06-06 01:54 UTC, chanwoo00106 approved these changes

2022-06-06 05:50 UTC, merged