Feat/check role
GSM-MSG/MSG-BackEnd-V2 pull request #140
Opened 2022-06-07 14:49 UTC by yoonjibin

applicant와 member을 다룰때 유저의 권한도 리턴이 되도록 수정했습니다

2022-06-07 14:49 UTC, baekteun approved these changes

2022-06-07 14:49 UTC, sagwamatrlawns approved these changes

2022-06-07 14:50 UTC, Huuuunee approved these changes

2022-06-07 14:51 UTC, an2434 approved these changes
good

2022-06-07 14:52 UTC, chanwoo00106 requested changes

2022-06-07 14:52 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    return { requestUser, userScope };
이거 명세서랑 다른 것 같은데

2022-06-07 14:54 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    return { requestUser, userScope };
정정할게 많이 복잡해짐

2022-06-07 14:55 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    return { requestUser, userScope };
```json
{
  requestUser: {...},
  userScope: "head"
}
```

2022-06-07 14:58 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    return { requestUser, userScope };
일단 이거 merge 하기 전에 api 명세서를 정확히 적을 필요가 있을 것 같음

2022-06-07 22:50 UTC, khs3994 approved these changes

2022-06-07 22:50 UTC, kimsh153 approved these changes

2022-06-07 23:26 UTC, an2434 approved these changes

2022-06-08 00:25 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    return { requestUser, userScope };
모르겠다 걍 이대로 하자

2022-06-08 00:25 UTC, chanwoo00106 approved these changes

2022-06-08 00:29 UTC, merged