Fix/apply
GSM-MSG/MSG-BackEnd-V2 pull request #153
Opened 2022-06-13 07:32 UTC by yoonjibin

#150 사설동아리에 복수로 가입하는 로직

2022-06-13 07:32 UTC, kimsh153 approved these changes

2022-06-13 07:34 UTC, baekteun commented on src/Club/club.service.ts
> +    const checkAplly = await this.RequestJoin.findOne({
apply

2022-06-13 07:35 UTC, khs3994 approved these changes

2022-06-13 08:06 UTC, sagwamatrlawns approved these changes

2022-06-13 09:17 UTC, chanwoo00106 approved these changes
이게 맞는지는 모르겠지만 믿는다

2022-06-13 12:04 UTC, chanwoo00106 reviewed
![image](https://user-images.githubusercontent.com/57276315/173349495-c919ab7b-362c-49a8-b79e-537d4a003adf.png)

위에 보면 email 체크 하는 거 있는데 이건 strategy에서 처리 하니깐 필요 없을 듯

2022-06-13 12:12 UTC, chanwoo00106 requested changes

2022-06-13 12:12 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +      return member.club.type === 'MAJOR' || 'FREEDOM';
이게 됨??
내가 봤을 땐 동아리 type이 major 만 거르는 것 같은데

2022-06-13 12:20 UTC, chanwoo00106 reviewed
지금 한 기능에 query가 3개 나 있는데 이거 잘 하면 줄일 수 있을 것 같음
한 번 노력해 보셈

2022-06-13 12:24 UTC, chanwoo00106 commented
처음에 클럽을 검색하는데 clubtype이랑 clubtitle이 이상한 값이면 어쩌려는 거야
query 후에 club에 값이 있는지 확인하는 게 필요할 듯

2022-06-13 12:25 UTC, chanwoo00106 commented
![image](https://user-images.githubusercontent.com/57276315/173352896-8c3289cc-c2cb-4ef5-9799-c30114914cc0.png)

그냥 dto를 `title`이랑 `type`으로 받으면 더 짧게 작성할 수 있을 것 같은데

2022-06-14 05:48 UTC, baekteun commented on src/Club/club.service.ts
> +        requestJoin.club.type === type && requestJoin.club.id === clubData.id
id면 이미 고유값 아님? 타입이랑 같이 검사하는거면 name끼리 비교해야 하지 않나

2022-06-14 07:07 UTC, louis7308 approved these changes

2022-06-14 07:09 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +      where: { type: type, title: title },
```suggestion
      where: { type, title },
```
이렇게

2022-06-14 07:21 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    let findOthers: any[];
타입은 정확히

2022-06-14 07:25 UTC, baekteun commented on src/Club/club.service.ts
> +      });
문득 생각났는데 find은 조건에 맞는 첫번째 값을 찾고 끝나는데 filter는 모든 요소 돌아서 거르는거니까 시간 조금이라도 더 아끼려면 find가 더 이득이지 않을까 조심스럽게 생각

2022-06-14 07:25 UTC, baekteun commented on src/Club/club.service.ts
> +      });
어차피 undefined인지 아닌지만 구분하는거니까

2022-06-14 07:31 UTC, chanwoo00106 commented on src/Club/club.service.ts
>      }
뭔가 더 예쁘게 짤 수 있을 것 같은데

2022-06-14 07:33 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +    const filterCheck = userData.requestJoin.filter((member) => {
변수 명이...

2022-06-14 07:35 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +        (member.club.type === 'MAJOR' || member.club.type === 'FREEDOM') &&
```suggestion
        member.club.type !== 'EDITORIAL' &&
```
이걸 하고 싶었던 게 맞습니까?

2022-06-14 07:37 UTC, chanwoo00106 commented on .github/workflows/node.js.yml
> +        node-version: [16.15.x]
이거 해결 좀 해봐

2022-06-14 07:38 UTC, chanwoo00106 commented on src/Club/club.service.ts
> +      where: { type: type, title: title },
```suggestion
      where: { type, title },
```

2022-06-14 07:44 UTC, chanwoo00106 commented on src/Club/club.service.ts
>        where: { email: acceptUserId },
이것도 그냥 email로 받는 게...

2022-06-14 07:49 UTC, chanwoo00106 commented
글고 pr 내용 좀 잘 써줘

2022-06-15 07:33 UTC, Huuuunee approved these changes

2022-06-16 07:58 UTC, chanwoo00106 approved these changes
지빈아 믿을 게

2022-06-16 08:27 UTC, merged